function [A,B] = LinFunc(in1,u,in3)
%LINFUNC
%    [A,B] = LINFUNC(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    01-Sep-2017 16:47:33

L = in3(1,:);
g = in3(2,:);
nu = in3(3,:);
theta = in1(1,:);
t2 = 1.0./L;
A = reshape([0.0,-g.*t2.*cos(theta),1.0,-nu],[2, 2]);
if nargout > 1
    B = [0.0;t2];
end
