function state_dot = PendulumDynamics(t,x)
%PENDULUMDYNAMICS
%    STATE_DOT = PENDULUMDYNAMICS(DP1,DP2,DP3,P2,P3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    07-Feb-2020 20:23:24


dp1 = x(1,1);
dp2 = x(2,1);
dp3 = x(3,1);
p2 = x(5,1);
p3 = x(6,1);

t9 = p2-p3;
t2 = cos(t9);
t3 = conj(p2);
t4 = conj(p3);
t5 = t3-t4;
t6 = sin(t5);
t7 = conj(dp2);
t8 = conj(dp3);
t10 = t2.^2;
t11 = t10-8.0;
t12 = 1.0./t11;
t13 = t6.*t7.*t8.*(1.0./2.0);
t14 = sin(t4);
t15 = t14.*(9.81e2./1.0e2);
t16 = dp2.*t6.*t8.*(1.0./2.0);
t17 = dp3.*t6.*t7.*(1.0./2.0);
t18 = -t13+t15+t16+t17;
t19 = sin(t3);
t20 = t19.*(9.81e2./5.0e1);
state_dot = [dp1;dp2;dp3;0.0;t12.*(t13+t20-dp2.*t6.*t8.*(1.0./2.0)-dp3.*t6.*t7.*(1.0./2.0)).*4.0-t2.*t12.*t18.*2.0;t12.*t18.*8.0-t2.*t12.*(t13-t16-t17+t20).*2.0];
